### PR TITLE
Improve file backup job to ignore tar warnings

### PR DESCRIPTION
**Pull request by Rade333**
**Changes proposed:**
- Append the drupal backup tar command in order to ignore tar exit code 1

**Reasoning:**

I noticed the backup cron job to fail multiple times, and the last line in logs was `backup tar: /app/web/sites/default/files: file changed as we read it`.

If any files change while tar is creating an archive, it will exit with code 1 and the rest of the backup job will not get run.
From [tar docs](https://www.gnu.org/software/tar/manual/html_section/Synopsis.html): 

> If tar was given ‘--create’, ‘--append’ or ‘--update’ option, this exit code [1] means that some files were changed while being archived and so the resulting archive does not contain the exact copy of the file set.

Changes are based on https://stackoverflow.com/a/49112839/12416374

### CODE REVIEW

**Comment by Jancis** [comment]
Would adding `--warning=no-file-changed` help in any way?
https://www.gnu.org/software/tar/manual/html_section/warnings.html

**Comment by Rade333** [comment]
> Would adding `--warning=no-file-changed` help in any way? https://www.gnu.org/software/tar/manual/html_section/warnings.html

@Jancis unfortunately no. That flag only affects the verbosity, so tar will not output the warning, but it does not affect the exit code.

**Comment by Jancis** [comment]
Looks good, just needs couple minor fixes - there is a double-space before first "or" and the second or with exit is missing a closing/wrapping parenthesis.

**Review by Jancis — CHANGES_REQUESTED** [review]
Looks good, just needs couple minor fixes - there is a double-space before first "or" and the second or with exit is missing a closing/wrapping parenthesis.

**Comment by Rade333** [comment]
> Looks good, just needs couple minor fixes - there is a double-space before first "or" and the second or with exit is missing a closing/wrapping parenthesis.

Good catch! Fixed!

**Review by Jancis — APPROVED** [review]

**Comment by Rade333** [comment]
Thank @Jancis for approval, however I'm not authorized to merge :)

**Comment by Jancis** [comment]
The dev workflow still needs some improvement. It will be merged a[nd credited](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) for the next chart release if that's alright.

**Comment by Rade333** [comment]
Sure thing!

**Comment by Jancis** [comment]
I tested backup changes in a dedicated branch, no regressions were noticed.

**Pull request merged**
